// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2ySipPG7JUr23elCGuMRqXnC7RRGM9k',
    appId: '1:308185640102:web:fbf4efcbc5a5c025e6d867',
    messagingSenderId: '308185640102',
    projectId: 'randoserunihongo-e7369',
    authDomain: 'randoserunihongo-e7369.firebaseapp.com',
    storageBucket: 'randoserunihongo-e7369.appspot.com',
    measurementId: 'G-GPFDQR52QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5of7_4eXXBaGpxWWID90KKymSKoB2z74',
    appId: '1:308185640102:android:918678a367edd08ce6d867',
    messagingSenderId: '308185640102',
    projectId: 'randoserunihongo-e7369',
    storageBucket: 'randoserunihongo-e7369.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADn6t87tdkWIN0XzR6cyhWW_B94lCuW8E',
    appId: '1:308185640102:ios:13ccaa2c435e3a3fe6d867',
    messagingSenderId: '308185640102',
    projectId: 'randoserunihongo-e7369',
    storageBucket: 'randoserunihongo-e7369.appspot.com',
    iosBundleId: 'com.example.randoselMain1',
  );
}
